### ISSUE TITLE
PAR from 08/06

### ISSUE THREAD

**Issue by holtzermann17** [supernovalex/dissertation_backup#1]
1. Review the intention: what do we expect to learn or make together?
- Improve clojure knowledge and skills: *
2. Establish what is happening: what and how are we learning?
- (*: Other tasks mostly set aside except briefly to touch upon)
- Watched "reveal" 15 minutes, with something to maybe follow up on about annotating everything - the video itself not exactly thrilling
- Watched zippers tutorial 1
- Did lots of hands on with zippers, threading, macroexpansion, 
- Watch 1st 15 minutes of Data-oriented Programming
3. What are some different perspectives on what’s happening?
- Joe: Liked the 15 minute taster, maybe we could have compressed it down to 5 minutes?
- Joe: I also liked the hands-on part but I did find it impossible to recreate the function from memory!
- Alex: I liked using tmate and screen again
- Joe: strict hygiene around (lf), we could possibly expand to multiple namespaces?
- Joe: very pleased to hear Orcro open to some clojure scripting!
4. What did we learn or change?
- Joe: feel I understand loops and zippers both better (syntax like let)
- Definitely learned something about threading anonymous functions!
- Alex: I learned how to jump to and from namespaces
5. What else should we change going forward?
- Alex busy until end of the week, save for briefly at 4PM today
- Joe will probably plan to attend M-x research on 'macros', if useful will report back
- Looking forward to compting Data Oriented Programming talk
- Joe@ Alex, maintain a breakdown of 'tools' in the disseration, maybe using a mindmap?
- As we're halfway through, we must cover a little bit of Evan Patterson's thesis
- Come Monday with an idea of biggest holes in Clojure knowledge (per 1. above)

**Comment by supernovalex** [comment]
No problem here, marking as closed! :)
